
WATSON_API_KEY = "2i7M1oiyhwXMHaeO1jOQkZdtHGjzCo_BreDibvSGn2cS"
WATSON_SERVICE_URL = "https://api.au-syd.natural-language-understanding.watson.cloud.ibm.com/instances/fbf08a4e-d409-4965-894d-347f8faabce1"